{ lib, pkgs, ... }:
let
  startupScript = pkgs.pkgs.writeShellScriptBin "start" ''
    ${pkgs.waybar}/bin/waybar &
    ${pkgs.networkmanager}/bin/nm-applet &
  '';
  lua = lib.generators.mkLuaInline;

  dispatch = command: lua "hl.dsp.exec_raw(${builtins.toJSON command})";
  exec = command: lua "hl.dsp.exec_cmd(${command})";
  focus = direction: lua "hl.dsp.focus({ direction = ${builtins.toJSON direction} })";
  swap = direction: lua "hl.dsp.window.swap({ direction = ${builtins.toJSON direction} })";
  resize =
    x: y: lua "hl.dsp.window.resize({ x = ${toString x}, y = ${toString y}, relative = true })";
  workspace = workspace: lua "hl.dsp.focus({ workspace = ${builtins.toJSON (toString workspace)} })";
  moveToWorkspace =
    workspace: lua "hl.dsp.window.move({ workspace = ${builtins.toJSON (toString workspace)} })";

  bind = keys: dispatcher: {
    _args = [
      keys
      dispatcher
    ];
  };

  bindExec = keys: command: bind keys (exec command);

  mouseBind = keys: dispatcher: {
    _args = [
      keys
      dispatcher
      { drag = true; }
    ];
  };
in
{
  home.packages = [
    pkgs.waybar
    pkgs.dunst
    pkgs.awww
    pkgs.hyprcursor
    pkgs.hyprpaper
    pkgs.hyprshot
  ];
  wayland.windowManager.hyprland = {

    enable = true;
    configType = "lua";

    settings = {
      # Custom variables
      mod._var = "SUPER";
      menu._var = "rofi -show drun -show-icons";
      terminal._var = "kitty";
      screenshot._var = "hyprshot";

      on = {
        _args = [
          "hyprland.start"
          (lua ''
            function()
              hl.exec_cmd(${builtins.toJSON "${startupScript}/bin/start"})
            end
          '')
        ];
      };
      monitor = [
        {
          output = "HDMI-A-2";
          mode = "3840x2160@144";
          position = "0x0";
          scale = 1;
        }
        {
          output = "Unknown-1"; # Disables phantom monitor that is probably generated by integrated AMD graphics
          disabled = true;
        }
      ];
      config = {
        # Visual appearance
        animations.enabled = false; # We want to be fast, not fancy!
        general = {
          gaps_in = 1;
          gaps_out = 1;
          col = {
            active_border = lua "{ colors = { colors.accent, colors.mauve }, angle = 45 }";
            inactive_border = lua "colors.surface0";
          };
        };
        # Should fix issues with not beign able to use dropdowns in zoom
        input = {
          follow_mouse = 1;
          mouse_refocus = false;
        };
      };
      # Keybinds
      bind = [
        (bindExec (lua ''mod .. " + RETURN"'') "terminal")
        (bindExec (lua ''mod .. " + D"'') "menu")
        # Screenshot options, I only need "select region really"
        (bindExec "PRINT" ''screenshot .. " -m region"'')
        # TODO: Reanable when I stop hitting that on accident
        # (bind (lua ''mod .. " + SHIFT + Q"'') (lua "hl.dsp.exit()"))
        (bind (lua ''mod .. " + SHIFT + E"'') (lua "hl.dsp.window.close()"))

        # Swich windows with arrow keys
        (bind (lua ''mod .. " + left"'') (focus "left"))
        (bind (lua ''mod .. " + right"'') (focus "right"))
        (bind (lua ''mod .. " + up"'') (focus "up"))
        (bind (lua ''mod .. " + down"'') (focus "down"))

        # Swapping windows
        (bind (lua ''mod .. " + ALT + left"'') (swap "left"))
        (bind (lua ''mod .. " + ALT + right"'') (swap "right"))
        (bind (lua ''mod .. " + ALT + up"'') (swap "up"))
        (bind (lua ''mod .. " + ALT + down"'') (swap "down"))

        # Moving/resizing windows
        (bind (lua ''mod .. " + SHIFT + right"'') (resize 40 0))
        (bind (lua ''mod .. " + SHIFT + left"'') (resize (-40) 0))
        (bind (lua ''mod .. " + SHIFT + up"'') (resize 0 (-40)))
        (bind (lua ''mod .. " + SHIFT + down"'') (resize 0 40))

        # Swith between floating and tiling windows
        (bind (lua ''mod .. " + SHIFT + F"'') (lua "hl.dsp.window.float({ action = \"toggle\" })"))

        # Volume key binds
        (bindExec "XF86AudioRaiseVolume" ''"wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"'')
        (bindExec "XF86AudioLowerVolume" ''"wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"'')
      ]
      ++ (
        # workspaces
        # binds $mod + [shift +] {1..9} to [move to] workspace {1..9}
        builtins.concatLists (
          builtins.genList (
            idx:
            let
              ws = idx + 1;
            in
            [
              (bind (lua ''mod .. " + ${toString ws}"'') (workspace ws))
              (bind (lua ''mod .. " + SHIFT + ${toString ws}"'') (moveToWorkspace ws))
            ]
          ) 9
        )
      )
      ++ [
        # Mouse binds
        (mouseBind (lua ''mod .. " + mouse:272"'') (dispatch "movewindow"))
        (mouseBind (lua ''mod .. " + mouse:273"'') (dispatch "resizeactive"))
      ];
      env = [
        {
          _args = [
            "HYPRCURSOR_THEME"
            "Bibata-Modern-Classic"
          ];
        }
        {
          _args = [
            "HYPRCURSOR_SIZE"
            "24"
          ];
        }
      ];
    };
  };
}
